

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"

  telegram-bot:
    container_name: telegram_bot
    build: .
    command: bash -c "make migrations && make migrate && make run_bot"
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  sender-service:
    container_name: sender-service
    build: .
    command: celery -A app worker -l info
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env
    depends_on:
      - postgres
      - telegram-bot
      - redis

  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A app beat -l info
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env
    depends_on:
      - postgres
      - telegram-bot
      - redis

  flower:
    container_name: flower
    build: .
    command: celery -A app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  postgres_data: 